fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.1.1
    hooks:
      - id: clang-format
        args:
          - -i
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
  - repo: local
    hooks:
      - id: headercheck
        name: Header Check
        language_version: "3.9"
        language: python
        entry: python3 ./headerCheck.py
